name: Publish Beta

on:
  push:
    branches:
      - develop

jobs:
  version-bump:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Instalar dependencias (incluyendo standard-version)
        run: bun install

      - name: Bump versi贸n usando standard-version
        run: |
          bunx standard-version --commit-all \
                               --prerelease \
                               --releaseCommitMessageFormat "chore(release): {{currentTag}} [skip ci]" \
                               --skip.changelog=true

      - name: Push cambios de versi贸n
        run: |
          git push --follow-tags origin HEAD:develop

  build-beta-windows:
    needs: version-bump

    runs-on: windows-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Setup Git (para que standard-version pueda hacer commit local)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install dependencies
        run: bun install
      - name: Mostrar nueva versi贸n
        run: cat package.json

      - name: Build & Publish Beta (Windows)
        run: |
          bun run build && bunx electron-builder --config electron-builder.config.js -w --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANNEL: beta
  build-beta-linux:
      needs: version-bump
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: "latest"

        - name: Setup Git
          run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

        - name: Install dependencies
          run: bun install
          
        - name: Mostrar nueva versi贸n
          run: cat package.json
  
        - name: Build & Publish Beta (Linux)
          run: |
            bun run build && bunx electron-builder --config electron-builder.config.js -l --publish always 
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CHANNEL: beta
